### ISSUE TITLE
[BUG] Cannot read properties of null (reading 'repositories')

### ISSUE THREAD

**Issue by hoangvictor** [yoshi389111/github-profile-3d-contrib#86]
**Describe the bug**
While running Github Actions in version 0.7.1, I encountered the following error:
```
Run yoshi389111/github-profile-3d-contrib@0.7.1
TypeError: Cannot read properties of null (reading 'repositories')
    at Object.fetchData (/home/runner/work/_actions/yoshi389111/github-profile-3d-contrib/0.7.1/dist/index.js:1430:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:9[5](https://github.com/hoangvictor/hoangvictor/actions/runs/12344687156/job/34447593527#step:3:6):5)
    at async Object.main (/home/runner/work/_actions/yoshi389111/github-profile-3d-contrib/0.7.1/dist/index.js:1507:2[6](https://github.com/hoangvictor/hoangvictor/actions/runs/12344687156/job/34447593527#step:3:7))
**Expected behavior**
A clear and concise description of what you expected to happen.
```

**Comment by yoshi389111** [comment]
@hoangvictor 
Thank you for reporting the bug.

I looked at your repository, and it seems to have been working fine since February 8th.

Did you make any changes around that time?

Or do you have any idea what could be causing this?

**Comment by hoangvictor** [comment]
It seems like the error dissapears:
![Image](https://github.com/user-attachments/assets/be3e0a64-6bd2-4867-a53c-c3498b738854)

**Comment by yoshi389111** [comment]
Thank you for your response.

Since there were no changes on your end at that time, it's unclear whether this was due to a latent bug or an issue on GitHub's side.

For now, I will close this issue.

Please feel free to reach out if you encounter any further problems.
